language: python

python:
  - 2.7

install:
  - pip install requests[security]
  - pip install httpie
  - pip install git+https://github.com/linkchecker/linkchecker.git

before_script:
  - pyenv versions
  - python --version
  - pip --version
  - pip list
  - linkchecker --version

script:
  - linkchecker --check-extern --ignore-url http://localhost:8082 --timeout 10 ./manual/
