language: minimal

addons:
  apt:
    update: true
    packages:
    - python-pip

before_script:
  - pip install --user requests[security]
  - pip install --user httpie
  - pip install --user linkchecker
  - python --version
  - pip --version
  - linkchecker --version

script:
  - linkchecker --check-extern --timeout 10 ./manual/
